// Headless demo data generator.
// Pushes Hablo delegate keys to oneofus, then writes signed contact statements via /write.
//
// Run via: bin/createSimpsonsContactData.sh       (emulator, --dart-define=EMULATOR=true)
//      or: bin/createSimpsonsContactData_prod.sh  (production, --dart-define=EMULATOR=false)
//
// Requires: lib/dev/simpsons_private_keys.dart (generated by the scripts above)

import 'dart:convert';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'package:hablotengo/constants.dart';
import 'package:hablotengo/firebase_options.dart';
import 'package:hablotengo/models/contact_statement.dart';
import 'package:hablotengo/models/hablo_statement.dart';
import 'package:hablotengo/dev/widget_runner.dart';
import 'package:hablotengo/dev/simpsons_private_keys.dart';
import 'package:oneofus_common/cached_source.dart';
import 'package:oneofus_common/channel_factory.dart';
import 'package:oneofus_common/cloud_functions_source.dart';
import 'package:oneofus_common/cloud_functions_writer.dart';
import 'package:oneofus_common/crypto/crypto.dart';
import 'package:oneofus_common/crypto/crypto25519.dart';
import 'package:oneofus_common/oou_signer.dart';
import 'package:oneofus_common/oou_verifier.dart';
import 'package:oneofus_common/trust_statement.dart';

const bool kEmulator = bool.fromEnvironment('EMULATOR', defaultValue: true);

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  } catch (e) {
    if (!e.toString().contains('duplicate-app')) rethrow;
  }
  TrustStatement.init();
  HabloStatement.init();
  channelFactory = ChannelFactory(kEmulator ? FireChoice.emulator : FireChoice.prod);
  channelFactory.register(
    kOneofusDomain,
    exportUrl: oneofusExportUrl(false),
    functionsUrl: oneofusWriteUrl(false),
    emulatorExportUrl: oneofusExportUrl(true),
    emulatorFunctionsUrl: oneofusWriteUrl(true),
  );
  runApp(WidgetRunner(scenario: _run));
}

Future<void> _run() async {
  for (final character in _simpsons) {
    final identity = await HabloIdentityKey.load(character.keyName);
    await identity.makeHabloDelegate();
    await identity._writeContact(character);
    // ignore: avoid_print
    print('${character.keyName}: done');
  }
  // ignore: avoid_print
  print('PASS');
}

// ─── HabloIdentityKey ────────────────────────────────────────────────────────

class HabloIdentityKey {
  final String name;
  final OouKeyPair _keyPair;
  final String token;

  Json? _delegatePubKeyJson;
  StatementSigner? _delegateSigner;

  HabloIdentityKey._(this.name, this._keyPair, this.token);

  static Future<HabloIdentityKey> load(String name) async {
    final keyData = kSimpsonsPrivateKeys[name];
    if (keyData == null) throw Exception('No private key for $name');
    final keyPairJson = ((keyData as Map)['keyPair'] as Map).cast<String, dynamic>();
    final keyPair = await crypto.parseKeyPair(keyPairJson);
    final token = keyData['token'] as String;
    return HabloIdentityKey._(name, keyPair, token);
  }

  Future<void> makeHabloDelegate() async {
    final identityPubKeyJson = await (await _keyPair.publicKey).json;

    // Reuse saved delegate key if available to avoid accumulating delegates.
    final savedDelegateData = kSimpsonsPrivateKeys['$name-hablo0'];
    final OouKeyPair delegateKeyPair;
    if (savedDelegateData != null) {
      final savedJson = ((savedDelegateData as Map)['keyPair'] as Map).cast<String, dynamic>();
      delegateKeyPair = await crypto.parseKeyPair(savedJson);
      // Already registered — skip publishing a new delegate statement.
    } else {
      delegateKeyPair = await crypto.createKeyPair();
      final delegatePubKeyJson = await (await delegateKeyPair.publicKey).json;
      final json = TrustStatement.make(
        identityPubKeyJson,
        delegatePubKeyJson,
        TrustVerb.delegate,
        domain: kHabloDomain,
      );
      final source = channelFactory.getChannel<TrustStatement>(kOneofusDomain, 'statements');
      final signer = await OouSigner.make(_keyPair);
      await source.fetch({Jsonish(json['I']).token: null});
      await source.push(json, signer);
    }

    _delegatePubKeyJson = await (await delegateKeyPair.publicKey).json;
    _delegateSigner = await OouSigner.make(delegateKeyPair);
    final delegateKeyPairJson = await delegateKeyPair.json;
    // ignore: avoid_print
    print('HABLO_DELEGATE:$name:${jsonEncode(delegateKeyPairJson)}');
    // ignore: avoid_print
    print('$name: delegate OK');
  }

  Future<void> _writeContact(_Character c) async {
    final identityPubKeyJson = await (await _keyPair.publicKey).json;
    final delegateToken = getToken(_delegatePubKeyJson!);
    final streamId = '${delegateToken}_$token';

    // Demo auth works in the emulator; production requires a real signed session.
    final Map<String, dynamic> authParams;
    if (kEmulator) {
      authParams = {'identity': identityPubKeyJson, 'demo': true};
    } else {
      final sessionTime = DateTime.now().toUtc().toIso8601String();
      final sessionSignature = await _keyPair.sign('hablotengo.com-$token-$sessionTime');
      authParams = {
        'identity': identityPubKeyJson,
        'sessionTime': sessionTime,
        'sessionSignature': sessionSignature,
      };
    }
    Map<String, dynamic> authHook() => authParams;

    final source = CloudFunctionsSource<HabloStatement>(
      baseUrl: habloExportUrl(kEmulator),
      verifier: OouVerifier(),
      authHook: authHook,
    );
    final writer = CloudFunctionsWriter<HabloStatement>(
      '${habloFunctionsBaseUrl(kEmulator)}/write',
      streamId,
      authHook: authHook,
    );
    final channel = CachedSource<HabloStatement>(source, writer);

    await channel.fetch({delegateToken: null});
    await channel.push(
      buildFullSetJson(
        set: {
          'name': c.displayName,
          if (c.notes != null) 'notes': c.notes,
          'entries': c.entries.map((e) => e.toJson()).toList(),
        },
        delegatePublicKeyJson: _delegatePubKeyJson!,
        identityToken: token,
      ),
      _delegateSigner!,
    );
    // ignore: avoid_print
    print('$name: contact OK');
  }
}

// ─── Character definitions ───────────────────────────────────────────────────

class _Character {
  final String keyName;
  final String displayName;
  final String? notes;
  final List<ContactEntry> entries;

  const _Character(this.keyName,
      {required this.displayName, this.notes, this.entries = const []});
}

const List<_Character> _simpsons = [
  _Character('homer',
      displayName: 'Homer Simpson',
      notes: "Never call me",
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-HOMER', preferred: true),
        ContactEntry(tech: 'email', value: 'homer@springfield-nuclear.gov'),
      ]),
  _Character('marge',
      displayName: 'Marge Simpson',
      notes: "Call me!!!",
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-MARGE', preferred: true),
        ContactEntry(tech: 'email', value: 'marge@simpsons.com'),
      ]),
  _Character('bart',
      displayName: 'Bart Simpson',
      notes: 'Eat my shorts.',
      entries: [
        ContactEntry(tech: 'email', value: 'bart@springfield-elementary.edu'),
        ContactEntry(tech: 'instagram', value: '@thrillhouse_bart'),
      ]),
  _Character('lisa',
      displayName: 'Lisa Simpson',
      entries: [
        ContactEntry(tech: 'email', value: 'lisa@simpsons.com', preferred: true),
        ContactEntry(tech: 'phone', value: '+1-555-LISA'),
      ]),
  _Character('maggie', displayName: 'Maggie Simpson'),
  _Character('milhouse',
      displayName: 'Milhouse Van Houten',
      entries: [
        ContactEntry(tech: 'email', value: 'milhouse@springfield-elementary.edu'),
      ]),
  _Character('luann',
      displayName: 'Luann Van Houten',
      notes: "Milhouse gets me on weekdays.",
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-LUANN', preferred: true),
        ContactEntry(tech: 'email', value: 'luann@springfield.net'),
      ]),
  _Character('nelson',
      displayName: 'Nelson Muntz',
      notes: 'Ha-HA!',
      entries: [
        ContactEntry(tech: 'email', value: 'nelson@springfield-elementary.edu'),
        ContactEntry(tech: 'instagram', value: '@ha_haa_muntz'),
      ]),
  _Character('lenny',
      displayName: 'Lenny Leonard',
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-LENNY', preferred: true),
        ContactEntry(tech: 'email', value: 'lenny@springfield-nuclear.gov'),
        ContactEntry(tech: 'signal', value: 'lenny.l'),
      ]),
  _Character('carl',
      displayName: 'Carl Carlson',
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-CARL', preferred: true),
        ContactEntry(tech: 'email', value: 'carl@springfield-nuclear.gov'),
      ]),
  _Character('burns',
      displayName: 'C. Montgomery Burns',
      notes: 'Contact through Smithers only. Do NOT call after 9 PM.',
      entries: [
        ContactEntry(tech: 'email', value: 'burns@springfield-nuclear.gov'),
        ContactEntry(tech: 'fax', value: '+1-555-BRNSFX'),
      ]),
  _Character('smithers',
      displayName: 'Waylon Smithers',
      notes: "If it's about Mr. Burns, I'm already on it.",
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-SMTHS', preferred: true),
        ContactEntry(tech: 'email', value: 'smithers@springfield-nuclear.gov'),
      ]),
  _Character('krusty',
      displayName: 'Krusty the Clown',
      notes: 'For bookings contact my agent.',
      entries: [
        ContactEntry(tech: 'email', value: 'krusty@krustybrand.com', preferred: true),
        ContactEntry(tech: 'fax', value: '+1-555-KRUST'),
        ContactEntry(tech: 'tiktok', value: '@therealKrustyKlown'),
      ]),
  _Character('sideshow',
      displayName: 'Sideshow Bob',
      notes: 'Do NOT leave me a voicemail about rakes.',
      entries: [
        ContactEntry(tech: 'email', value: 'r.terwilliger@springfield-arts.org', preferred: true),
        ContactEntry(tech: 'phone', value: '+1-555-TBOB'),
      ]),
  _Character('seymore',
      displayName: 'Seymour Skinner',
      notes: 'Mother screens my calls before 8 AM.',
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-SKNNR', preferred: true),
        ContactEntry(tech: 'email', value: 'principal@springfield-elementary.edu'),
        ContactEntry(tech: 'email', value: 'armin.tanzarian@gmail.com'),
      ]),
];
