// Headless demo data generator.
// Pushes Hablo delegate keys to oneofus, then writes signed contact statements via /write.
//
// Run via: bin/createSimpsonsContactData.sh       (emulator, --dart-define=EMULATOR=true)
//      or: bin/createSimpsonsContactData_prod.sh  (production, --dart-define=EMULATOR=false)
//
// Requires: lib/dev/simpsons_private_keys.dart (generated by the scripts above)

import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

import 'package:hablotengo/constants.dart';
import 'package:hablotengo/models/contact_statement.dart';
import 'package:hablotengo/dev/widget_runner.dart';
import 'package:hablotengo/dev/simpsons_private_keys.dart';
import 'package:oneofus_common/cached_source.dart';
import 'package:oneofus_common/cloud_functions_source.dart';
import 'package:oneofus_common/cloud_functions_writer.dart';
import 'package:oneofus_common/crypto/crypto.dart';
import 'package:oneofus_common/crypto/crypto25519.dart';
import 'package:oneofus_common/oou_signer.dart';
import 'package:oneofus_common/oou_verifier.dart';
import 'package:oneofus_common/trust_statement.dart';

const bool kEmulator = bool.fromEnvironment('EMULATOR', defaultValue: true);

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  TrustStatement.init();
  runApp(WidgetRunner(scenario: _run));
}

Future<void> _run() async {
  for (final character in _simpsons) {
    final identity = await HabloIdentityKey.load(character.keyName);
    await identity.makeHabloDelegate();
    await identity._writeContact(character);
    // ignore: avoid_print
    print('${character.keyName}: done');
  }
  // ignore: avoid_print
  print('PASS');
}

// ─── HabloIdentityKey ────────────────────────────────────────────────────────

class HabloIdentityKey {
  final String name;
  final OouKeyPair _keyPair;
  final String token;

  Json? _delegatePubKeyJson;
  StatementSigner? _delegateSigner;

  HabloIdentityKey._(this.name, this._keyPair, this.token);

  static Future<HabloIdentityKey> load(String name) async {
    final keyData = kSimpsonsPrivateKeys[name];
    if (keyData == null) throw Exception('No private key for $name');
    final keyPairJson = ((keyData as Map)['keyPair'] as Map).cast<String, dynamic>();
    final keyPair = await crypto.parseKeyPair(keyPairJson);
    final token = keyData['token'] as String;
    return HabloIdentityKey._(name, keyPair, token);
  }

  Future<void> makeHabloDelegate() async {
    final identityPubKeyJson = await (await _keyPair.publicKey).json;

    // Reuse saved delegate key if available to avoid accumulating delegates.
    final savedDelegateData = kSimpsonsPrivateKeys['$name-hablo0'];
    final OouKeyPair delegateKeyPair;
    if (savedDelegateData != null) {
      final savedJson = ((savedDelegateData as Map)['keyPair'] as Map).cast<String, dynamic>();
      delegateKeyPair = await crypto.parseKeyPair(savedJson);
      // Already registered — skip publishing a new delegate statement.
    } else {
      delegateKeyPair = await crypto.createKeyPair();
      final delegatePubKeyJson = await (await delegateKeyPair.publicKey).json;
      final json = TrustStatement.make(
        identityPubKeyJson,
        delegatePubKeyJson,
        TrustVerb.delegate,
        domain: kHabloDomain,
      );
      final source = CachedSource<TrustStatement>(
        CloudFunctionsSource<TrustStatement>(
          baseUrl: oneofusExportUrl(kEmulator),
          verifier: OouVerifier(),
        ),
        CloudFunctionsWriter<TrustStatement>(oneofusWriteUrl(kEmulator), 'statements'),
      );
      final signer = await OouSigner.make(_keyPair);
      await source.fetch({Jsonish(json['I']).token: null});
      await source.push(json, signer);
    }

    _delegatePubKeyJson = await (await delegateKeyPair.publicKey).json;
    _delegateSigner = await OouSigner.make(delegateKeyPair);
    final delegateKeyPairJson = await delegateKeyPair.json;
    // ignore: avoid_print
    print('HABLO_DELEGATE:$name:${jsonEncode(delegateKeyPairJson)}');
    // ignore: avoid_print
    print('$name: delegate OK');
  }

  Future<void> _writeContact(_Character c) async {
    final identityPubKeyJson = await (await _keyPair.publicKey).json;
    final channel = _DemoHabloChannel(
      baseUrl: habloFunctionsBaseUrl(kEmulator),
      identityJson: identityPubKeyJson,
      delegatePubKeyJson: _delegatePubKeyJson!,
      signer: _delegateSigner!,
    );

    await channel.push(buildSetFieldJson(
      field: 'name',
      value: c.displayName,
      delegatePublicKeyJson: _delegatePubKeyJson!,
      identityToken: token,
    ));
    if (c.notes != null) {
      await channel.push(buildSetFieldJson(
        field: 'notes',
        value: c.notes!,
        delegatePublicKeyJson: _delegatePubKeyJson!,
        identityToken: token,
      ));
    }
    for (int i = 0; i < c.entries.length; i++) {
      final entry = c.entries[i].copyWith(order: (i + 1).toDouble());
      await channel.push(buildSetEntryJson(
        entry: entry,
        delegatePublicKeyJson: _delegatePubKeyJson!,
        identityToken: token,
      ));
    }
    // ignore: avoid_print
    print('$name: contact OK');
  }
}

// ─── Demo channel (mirrors HabloChannel but uses demo auth) ──────────────────

class _DemoHabloChannel {
  final String _baseUrl;
  final Json _identityJson;
  final Json _delegatePubKeyJson;
  final StatementSigner _signer;

  String? _head;
  bool _headLoaded = false;
  Future<void> _writeQueue = Future.value();

  _DemoHabloChannel({
    required String baseUrl,
    required Json identityJson,
    required Json delegatePubKeyJson,
    required StatementSigner signer,
  })  : _baseUrl = baseUrl,
        _identityJson = identityJson,
        _delegatePubKeyJson = delegatePubKeyJson,
        _signer = signer;

  Map<String, dynamic> get _authPayload => {'identity': _identityJson, 'demo': true};

  Future<String> push(Json json) {
    final completer = Completer<String>();
    _writeQueue = _writeQueue.catchError((_) {}).then((_) async {
      try {
        await _ensureHead();
        final Json j = Map.from(json);
        if (_head != null) j['previous'] = _head!;
        final Jsonish jsonish = await Jsonish.makeSign(j, _signer);
        await _callWrite(jsonish);
        _head = jsonish.token;
        completer.complete(jsonish.token);
      } catch (e, st) {
        completer.completeError(e, st);
      }
    });
    return completer.future;
  }

  Future<void> _ensureHead() async {
    if (_headLoaded) return;
    await _fetchHead();
  }

  Future<void> _fetchHead() async {
    try {
      final delegateToken = getToken(_delegatePubKeyJson);
      final response = await http.post(
        Uri.parse('$_baseUrl/getStreamHead'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({..._authPayload, 'delegateToken': delegateToken}),
      );
      if (response.statusCode == 200) {
        final data = jsonDecode(response.body) as Map<String, dynamic>;
        _head = data['token'] as String?;
      } else {
        // ignore: avoid_print
        print('_DemoHabloChannel: getStreamHead ${response.statusCode} ${response.body}');
      }
    } catch (e) {
      // ignore: avoid_print
      print('_DemoHabloChannel: getStreamHead error: $e');
    } finally {
      _headLoaded = true;
    }
  }

  Future<void> _callWrite(Jsonish jsonish) async {
    final response = await http.post(
      Uri.parse('$_baseUrl/write'),
      headers: {'Content-Type': 'application/json'},
      body: jsonEncode({
        'statement': jsonish.json,
        ..._authPayload,
      }),
    );
    if (response.statusCode != 200) {
      throw Exception('write failed: ${response.statusCode} ${response.body}');
    }
  }
}

// ─── Character definitions ───────────────────────────────────────────────────

class _Character {
  final String keyName;
  final String displayName;
  final String? notes;
  final List<ContactEntry> entries;

  const _Character(this.keyName,
      {required this.displayName, this.notes, this.entries = const []});
}

const List<_Character> _simpsons = [
  _Character('homer',
      displayName: 'Homer Simpson',
      notes: "Never call me",
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-HOMER', preferred: true),
        ContactEntry(tech: 'email', value: 'homer@springfield-nuclear.gov'),
      ]),
  _Character('marge',
      displayName: 'Marge Simpson',
      notes: "Call me!!!",
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-MARGE', preferred: true),
        ContactEntry(tech: 'email', value: 'marge@simpsons.com'),
      ]),
  _Character('bart',
      displayName: 'Bart Simpson',
      notes: 'Eat my shorts.',
      entries: [
        ContactEntry(tech: 'email', value: 'bart@springfield-elementary.edu'),
        ContactEntry(tech: 'instagram', value: '@thrillhouse_bart'),
      ]),
  _Character('lisa',
      displayName: 'Lisa Simpson',
      entries: [
        ContactEntry(tech: 'email', value: 'lisa@simpsons.com', preferred: true),
        ContactEntry(tech: 'phone', value: '+1-555-LISA'),
      ]),
  _Character('maggie', displayName: 'Maggie Simpson'),
  _Character('milhouse',
      displayName: 'Milhouse Van Houten',
      entries: [
        ContactEntry(tech: 'email', value: 'milhouse@springfield-elementary.edu'),
      ]),
  _Character('luann',
      displayName: 'Luann Van Houten',
      notes: "Milhouse gets me on weekdays.",
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-LUANN', preferred: true),
        ContactEntry(tech: 'email', value: 'luann@springfield.net'),
      ]),
  _Character('nelson',
      displayName: 'Nelson Muntz',
      notes: 'Ha-HA!',
      entries: [
        ContactEntry(tech: 'email', value: 'nelson@springfield-elementary.edu'),
        ContactEntry(tech: 'instagram', value: '@ha_haa_muntz'),
      ]),
  _Character('lenny',
      displayName: 'Lenny Leonard',
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-LENNY', preferred: true),
        ContactEntry(tech: 'email', value: 'lenny@springfield-nuclear.gov'),
        ContactEntry(tech: 'signal', value: 'lenny.l'),
      ]),
  _Character('carl',
      displayName: 'Carl Carlson',
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-CARL', preferred: true),
        ContactEntry(tech: 'email', value: 'carl@springfield-nuclear.gov'),
      ]),
  _Character('burns',
      displayName: 'C. Montgomery Burns',
      notes: 'Contact through Smithers only. Do NOT call after 9 PM.',
      entries: [
        ContactEntry(tech: 'email', value: 'burns@springfield-nuclear.gov'),
        ContactEntry(tech: 'fax', value: '+1-555-BRNSFX'),
      ]),
  _Character('smithers',
      displayName: 'Waylon Smithers',
      notes: "If it's about Mr. Burns, I'm already on it.",
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-SMTHS', preferred: true),
        ContactEntry(tech: 'email', value: 'smithers@springfield-nuclear.gov'),
      ]),
  _Character('krusty',
      displayName: 'Krusty the Clown',
      notes: 'For bookings contact my agent.',
      entries: [
        ContactEntry(tech: 'email', value: 'krusty@krustybrand.com', preferred: true),
        ContactEntry(tech: 'fax', value: '+1-555-KRUST'),
        ContactEntry(tech: 'tiktok', value: '@therealKrustyKlown'),
      ]),
  _Character('sideshow',
      displayName: 'Sideshow Bob',
      notes: 'Do NOT leave me a voicemail about rakes.',
      entries: [
        ContactEntry(tech: 'email', value: 'r.terwilliger@springfield-arts.org', preferred: true),
        ContactEntry(tech: 'phone', value: '+1-555-TBOB'),
      ]),
  _Character('seymore',
      displayName: 'Seymour Skinner',
      notes: 'Mother screens my calls before 8 AM.',
      entries: [
        ContactEntry(tech: 'phone', value: '+1-555-SKNNR', preferred: true),
        ContactEntry(tech: 'email', value: 'principal@springfield-elementary.edu'),
        ContactEntry(tech: 'email', value: 'armin.tanzarian@gmail.com'),
      ]),
];
